<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Permission Matrix
    |--------------------------------------------------------------------------
    |
    | Each resource exposes explicit actions. Effective permissions are
    | evaluated per-tenant from assigned custom roles.
    |
    */
    'resources' => [
        'dashboard' => ['view'],
        'leads' => ['view', 'create', 'update', 'delete', 'export'],
        'accounts' => ['view', 'create', 'update', 'delete', 'link'],
        'tracking' => ['view', 'create', 'update', 'export'],
        'personalization' => ['view', 'create', 'update', 'delete', 'publish'],
        'portal_requests' => ['view', 'create', 'update', 'delete', 'convert'],
        'data_quality' => ['view', 'create', 'update', 'delete', 'review'],
        'experiments' => ['view', 'create', 'update', 'delete', 'publish'],
        'marketplace' => ['view', 'create', 'update', 'delete', 'install'],
        'copilot' => ['view', 'create', 'update'],
        'segments' => ['view', 'create', 'update', 'delete', 'export'],
        'templates' => ['view', 'create', 'update', 'delete', 'export', 'send'],
        'playbooks' => ['view', 'create', 'update', 'delete', 'suggest'],
        'campaigns' => ['view', 'create', 'update', 'delete', 'export', 'send'],
        'assignment_rules' => ['view', 'create', 'update', 'delete'],
        'settings' => ['view', 'update'],
        'webhooks' => ['view', 'export'],
        'api_keys' => ['view', 'create', 'update', 'delete'],
        'roles' => ['view', 'create', 'update', 'delete', 'assign'],
        'inbox' => ['view', 'update'],
        'consent' => ['view', 'update', 'export'],
        'compliance' => ['view', 'create', 'update', 'delete'],
        'billing' => ['view', 'create', 'update', 'delete', 'export'],
        'integrations' => ['view', 'create', 'update', 'delete'],
        'sso' => ['view', 'create', 'update', 'delete'],
        'sandboxes' => ['view', 'create', 'update', 'delete', 'promote'],
        'custom_fields' => ['view', 'create', 'update', 'delete'],
        'forms' => ['view', 'create', 'update', 'delete'],
        'workflows' => ['view', 'create', 'update', 'approve', 'publish', 'rollback'],
        'realtime' => ['view'],
        'calls' => ['view', 'create', 'update', 'delete'],
        'telephony' => ['view', 'create', 'update'],
        'health' => ['view'],
        'exports' => ['view', 'create', 'download'],
        'approvals' => ['view', 'review'],
        'ai' => ['view', 'create'],
        'lifecycle' => ['view', 'update', 'delete', 'export'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Role Templates
    |--------------------------------------------------------------------------
    |
    | Tenant bootstrapping templates. Templates are safe defaults and can be
    | copied/extended per tenant.
    |
    */
    'templates' => [
        'sales' => [
            'name' => 'Sales',
            'description' => 'Lead follow-up and day-to-day sales execution.',
            'permissions' => [
                'dashboard.view',
                'leads.view',
                'leads.create',
                'leads.update',
                'accounts.view',
                'accounts.link',
                'tracking.view',
                'copilot.view',
                'copilot.create',
                'campaigns.view',
                'templates.view',
                'playbooks.view',
                'playbooks.suggest',
                'segments.view',
                'inbox.view',
                'calls.view',
                'calls.create',
            ],
        ],
        'manager' => [
            'name' => 'Manager',
            'description' => 'Pipeline and team management with export access.',
            'permissions' => [
                'dashboard.view',
                'leads.view',
                'leads.create',
                'leads.update',
                'leads.delete',
                'leads.export',
                'accounts.view',
                'accounts.create',
                'accounts.update',
                'accounts.link',
                'tracking.view',
                'tracking.export',
                'portal_requests.view',
                'portal_requests.convert',
                'data_quality.view',
                'data_quality.review',
                'copilot.view',
                'copilot.create',
                'segments.view',
                'segments.create',
                'segments.update',
                'segments.export',
                'templates.view',
                'templates.create',
                'templates.update',
                'playbooks.view',
                'playbooks.create',
                'playbooks.update',
                'playbooks.suggest',
                'campaigns.view',
                'campaigns.create',
                'campaigns.update',
                'campaigns.send',
                'assignment_rules.view',
                'inbox.view',
                'inbox.update',
                'calls.view',
                'calls.create',
                'calls.update',
                'exports.view',
                'exports.create',
                'exports.download',
                'approvals.view',
                'approvals.review',
            ],
        ],
        'marketing' => [
            'name' => 'Marketing',
            'description' => 'Audience segmentation, content, campaign orchestration.',
            'permissions' => [
                'dashboard.view',
                'leads.view',
                'leads.export',
                'accounts.view',
                'tracking.view',
                'tracking.export',
                'personalization.view',
                'personalization.create',
                'personalization.update',
                'experiments.view',
                'experiments.create',
                'experiments.update',
                'segments.view',
                'segments.create',
                'segments.update',
                'segments.delete',
                'segments.export',
                'templates.view',
                'templates.create',
                'templates.update',
                'templates.delete',
                'templates.export',
                'templates.send',
                'playbooks.view',
                'playbooks.create',
                'playbooks.update',
                'playbooks.delete',
                'playbooks.suggest',
                'campaigns.view',
                'campaigns.create',
                'campaigns.update',
                'campaigns.delete',
                'campaigns.export',
                'campaigns.send',
                'webhooks.view',
                'webhooks.export',
                'workflows.view',
                'workflows.create',
                'workflows.update',
                'workflows.publish',
                'approvals.view',
                'ai.view',
                'ai.create',
                'copilot.view',
                'copilot.create',
            ],
        ],
        'admin' => [
            'name' => 'Admin',
            'description' => 'Full tenant administration, integrations and role management.',
            'permissions' => ['*'],
        ],
    ],
];
